### ISSUE TITLE
How to create SAML 2.0 Advanced connector?

### ISSUE THREAD

**Issue by gmlexx** [onelogin/onelogin-go-sdk#16]
Hello,

Is there any way to create a new app with connector_id = 110016 with defined configuration?

Currently I can create an app with empty logout_url, audience, consumer_url, etc configuration fields

```
  "configuration": {
    "logout_url": "https://{{ website_name}}.{{ website_domain}}/auth/?sls",
    "saml_notonorafter": "3",
    "audience": "https://{{ website_name}}.{{ website_domain}}/auth/metadata/",
    "generate_attribute_value_tags": "0",
    "saml_initiater_id": "0",
    "saml_notbefore": "3",
    "saml_issuer_type": "0",
    "saml_sign_element": "0",
    "encrypt_assertion": "1",
    "consumer_url": "https://{{ website_name}}.{{ website_domain}}/auth/?acs",
    "login": "https://{{ website_name}}.{{ website_domain}}/",
    "saml_sessionnotonorafter": "1440",
    "saml_encryption_method_id": "0",
    "recipient": "https://{{ website_name}}.{{ website_domain}}/auth/?acs",
    "validator": ".*",
    "signature_algorithm": "SHA-1",
    "relaystate": "https://{{ website_name}}.{{ website_domain}}/",
    "saml_nameid_format_id": "0"
  }
```

**Comment by gmlexx** [comment]
@dcaponi @bplower any ideas?

**Comment by dcaponi** [comment]
@gmlexx I'm not sure what exactly you mean? Are you trying to use this SDK in a Golang project to manage OneLogin resources? If so, please refer to the [developer documentation](https://developers.onelogin.com/api-docs/2/apps/create-app) for interacting with the API. You'll likely have to translate some of your field names (e.g. audience => metadata_url).

With the fields you have here, I doubt its possible considering the app model in the API lacks a lot of the fields you sent here. I also don't know what kind of an app has connector_id 110016 (maybe because we're in different regions). You can get a better idea of how to create those apps if you crate a test app in the UI and then request it via the API using the GET request described in the documentation.

**Comment by gmlexx** [comment]
@dcaponi I'm trying to use terraform provider https://github.com/onelogin/terraform-provider-onelogin
This provider utilizes this SDK.
As per my understanding, this structure  https://github.com/onelogin/onelogin-go-sdk/blob/38fc8b46f507ced3f4014755764ad4c6bcdd1f7d/pkg/services/apps/model.go#L61
doesn't allow you to put arbitrary fields to API request.
connector_id 110016 is in US region "SAML Test Connector (Advanced)"

The fields json I pasted above is exactly what we get, when we do GET request after creating application manually with UI.
So, does it make sense to extend the model with map[string][string] structure or you have better idea how to solve this issue?

**Comment by dcaponi** [comment]
@gmlexx Makes sense, we actually made modifications to the Terraform provider to support this. The outstanding piece I need to confirm with our API team is whether or not, those fields you mention can be updated via the API. Based on the documentation, and what I've been told, SAML configuration fields that can be altered via the API are just the `signature_algorithm` and the `provider_arn` for AWS. It's likely possible those fields are changeable too, but I don't want to give you any misleading information there.

Once I confirm, it should be pretty straightforward to simply add those fields.

**Comment by gmlexx** [comment]
Thanks @dcaponi, these fields definitely can be updated via API, because this is our current approach to manage application with Ansible, where we simply send this Json with http module.
But since we are moving from Ansible to Terraform, would be nice to have this module for Onelogin as well.

**Comment by dcaponi** [comment]
Was just able to corroborate that on my side as well. We'll work on it; should be available soon :) 

I'll update here once it ships.

**Comment by dcaponi** [comment]
@gmlexx congrats, new version of the terraform provider is out with your added fields https://github.com/onelogin/terraform-provider-onelogin/releases/tag/v0.0.10

Thank you for your contribution :)

**Comment by gmlexx** [comment]
Thanks Dominick!

**Comment by artemsablin** [comment]
@dcaponi Hi, do you have any news about the public_key field API support?

**Comment by dcaponi** [comment]
hey @artemsablin I was just talking to our API time about this. Is the public_key to which you're referring for encryption or is this the SAML signature key? (The API currently renders the SAML signature key). In the encryption scenario we'd need to add that as an api-exposed field

**Comment by artemsablin** [comment]
This is the SP-provided public key that OneLogin would use to verify that the SP signed the assertion correctly. For now we have to create the SAML connector via API and then manually add that public key by hand which is not ideal.

In this [comment](https://github.com/onelogin/onelogin-go-sdk/issues/19#issuecomment-679191141) earlier you mention there is a ticket to make this accessible in your API. Was hoping for an update to the API so we can fully automate creating those SAML connectors.
