### ISSUE TITLE
What is the SAML Encryption public key configuration field?

### ISSUE THREAD

**Issue by gmlexx** [onelogin/onelogin-go-sdk#19]
Hi @dcaponi, @bplower 

This field is not documented and even if I do API app get, I don't see this field in the output.

In the UI this is the field for SAML Test Connector (Advanced) to put the certificate for assertion encryption.

![image](https://user-images.githubusercontent.com/1112318/89642531-a9a78200-d8bc-11ea-94c7-3f4f6dd18499.png)

**Comment by gmlexx** [comment]
Hi @dcaponi, @bplower. This is really the latest piece of information that we need to wrap up our deployment automation.
Thanks in advance.

**Comment by dcaponi** [comment]
Going to consolidate this question into this issue https://github.com/onelogin/onelogin-go-sdk/issues/16

This is the `public_key` field that needs to be exposed on the API side. There's a ticket in our kanban for it and we'll update you when that ships.
