### ISSUE TITLE
SAML assertion

### ISSUE THREAD

**Issue by braun1928** [onelogin/onelogin-go-sdk#31]
Hi, I forked the project to try and add SAML assertion support, as I'm trying to migrate a Python application that requires this. 
It basically works, as long as I don't have an error during the authentication, as it enters a loop in `olhttp.executeHTTP` to try and fetch a new Bearer token -- it doesn't distinguish between a SAML authn error and a OAuth one.

Check PR #30 as an initial work. The diff in `client.go` is due to VS Code import reordering.

**Comment by Jmfwolf** [comment]
@braun1928 would you be willing to try the latest version of the Go SDK and see if it resolves this issue?

**Comment by braun1928** [comment]
Hey @Jmfwolf I unfortunately cannot The company I work in has moved from OL to Okta, so this is not an issue for me anymore. We can close the issue if this is not impacting others, too.
