### ISSUE TITLE
Switch out dgrijalva/jwt-go to golang-jwt/jwt

### ISSUE THREAD

**Issue by delwaterman** [onelogin/onelogin-go-sdk#41]
The [dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go#this-repository-is-no-longer-maintaned) is no longer maintained and has security issues.

Switch to [golang-jwt/jwt](https://github.com/golang-jwt/jwt) instead.

**Comment by dcaponi** [comment]
Hey @delwaterman where is this package being used? I tried doing a search but I dont see it anywhere. Do you have the right repo?

**Comment by delwaterman** [comment]
Nope this was entirely wrong on my part. My apologies.
