### ISSUE TITLE
Bug on usage of Queryable (interface) feature(s)

### ISSUE THREAD

**Issue by siryur** [onelogin/onelogin-go-sdk#74]
### On Validators
QueryValidators are not taking into consideration the pointer types.
Take into consideration the [UserQuery.email](https://github.com/onelogin/onelogin-go-sdk/blob/cd301aef8cdd2e27ab1514d4fd1718941e9d87dc/pkg/onelogin/models/user.go#L99), that matches the for the [validation.validateString](https://github.com/onelogin/onelogin-go-sdk/blob/cd301aef8cdd2e27ab1514d4fd1718941e9d87dc/pkg/onelogin/models/validation.go#L11-L15) validates a string, but the query struct olds a (pointer) `*string`:
```go
type UserQuery struct {
        // ... other values
        Email          *string    `json:"email,omitempty"`
        // ... other values
}

func (q *UserQuery) GetKeyValidators() map[string]func(interface{}) bool {
	return map[string]func(interface{}) bool{
		// ... other values
		"email":          validateString,
		// ... other values
	}
}

func validateString(val interface{}) bool {
	_, ok := val.(string)
	return ok
}
```

A simple example (given mostly from the docs example), proves that failure:
```go
func main() {
	ol, err := onelogin.NewOneloginSDK()
	if err != nil {
		fmt.Println("Unable to initialize client:", err)
		return
	}

	email := "test@test.com"
	userQuery := &models.UserQuery{
		Email: &email,
	}
	userList, err := ol.GetUsers(userQuery)
	if err != nil {
		fmt.Println("Failed to get user:", err) // <-- enters here
		return
	}

	fmt.Println(userList)
}
```

Although this was just tested with the example provided,
I believe this can be happening in more places.

### On request payload
Keeping the same example as the above, even if the validators are bypassed, when we are trying to setup the request to be made, the [AddQueryToPath](https://github.com/onelogin/onelogin-go-sdk/blob/cd301aef8cdd2e27ab1514d4fd1718941e9d87dc/pkg/onelogin/utilities/web.go#L82-L100) invoking its neighbour function [queryToValues](https://github.com/onelogin/onelogin-go-sdk/blob/cd301aef8cdd2e27ab1514d4fd1718941e9d87dc/pkg/onelogin/utilities/web.go#L102-L118) fail to setup the URL query parameters from the `Queryable` interface previously given to it.

### Extra
- Is there any other way of using this?
- Can someone share a workable snippet?

**Comment by Jmfwolf** [comment]
Thank you for this. I will keep you posted on this.
