### ISSUE TITLE
AddRoleUsers (and other functionalities) doesn't seem to match the API documentation 

### ISSUE THREAD

**Issue by thisiseyal** [onelogin/onelogin-go-sdk#84]
Just as an example, when looking at v2 API documentation vs. the code implementation -> `AddRoleUsers` doesn't accept any users as input. We can also see it in `AddRoleAdmins`, didn't go through all modules but I imagine it might exist in other methods too.

According to [documentation](https://developers.onelogin.com/api-docs/2/roles/add-role-users), it is a POST request, and there should be an array of user_ids in data.

The postman collection of their latest version (https://www.postman.com/onelogin/onelogin-s-public-workspace/request/9dtq3tg/add-role-users) could be a good reference as well, to compare the current implementation methods and parameters with theirs.

Thanks~

**Comment by Subterrane** [comment]
Fixed https://github.com/onelogin/onelogin-go-sdk/pull/85
